apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app: {{ include "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install
data:
  connect.elastic.xpack.settings: {{ .Values.xpackSettings | b64enc }}
